version: "3"

vars:
  SERVICES: auth

tasks:
  default:
    desc: Show available tasks
    cmds: [ task --list ]

  setup:
    desc: Sync workspace and install tools
    cmds:
      - go work sync
      - task: install-tools
      - task: generate-proto

  install-tools:
    desc: Install required development tools
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

  generate-proto:
    desc: Generate Go code from all proto files
    dir: pkg/proto
    cmds:
      - task: generate-proto-auth
      - task: generate-proto-common
    sources:
      - "**/*.proto"
    generates:
      - "**/*.pb.go"
      - "**/*_grpc.pb.go"

  generate-proto-auth:
    desc: Generate Go code for auth service proto
    dir: pkg/proto
    cmds:
      - |
        protoc \
          --go_out=. \
          --go_opt=paths=source_relative \
          --go-grpc_out=. \
          --go-grpc_opt=paths=source_relative \
          auth/auth.proto
    sources:
      - auth/auth.proto
    generates:
      - auth/auth.pb.go
      - auth/auth_grpc.pb.go

  generate-proto-common:
    desc: Generate Go code for common proto messages
    dir: pkg/proto
    cmds:
      - |
        protoc \
          --go_out=. \
          --go_opt=paths=source_relative \
          --go-grpc_out=. \
          --go-grpc_opt=paths=source_relative \
          common/common.proto
    sources:
      - common/common.proto
    generates:
      - common/common.pb.go
      - common/common_grpc.pb.go

  build:
    cmds:
      - for: { var: SERVICES }
        cmd: task build-service SERVICE={{.ITEM}}

  build-service:
    vars: { SERVICE: "" }
    cmds:
      - cd services/{{.SERVICE}} && go build -o bin/{{.SERVICE}} ./cmd

  test:
    cmds: [ go test ./... ]

  docker-build:
    cmds:
      - for: { var: SERVICES }
        cmd: docker build -f services/{{.ITEM}}/Dockerfile -t go-factory-{{.ITEM}}:latest .

  docker-up:
    cmds: [ docker-compose up -d ]

  docker-down:
    cmds: [ docker-compose down ]

  clean:
    desc: Clean build artifacts and containers
    cmds:
      - task: clean-build
      - task: clean-proto
      - task: clean-docker

  clean-build:
    desc: Clean build artifacts
    cmds:
      - for: { var: SERVICES }
        cmd: cd services/{{.ITEM}} && Remove-Item -Recurse -Force bin -ErrorAction SilentlyContinue

  clean-proto:
    desc: Clean generated proto files
    dir: pkg/proto
    cmds:
      - Remove-Item -Force "**/*.pb.go" -ErrorAction SilentlyContinue

  clean-docker:
    desc: Stop and remove containers with volumes
    cmds:
      - docker-compose down --volumes --remove-orphans

  mod-tidy:
    desc: Run go mod tidy on all modules
    cmds:
      - cd pkg/common && go mod tidy
      - cd pkg/proto && go mod tidy
      - for: { var: SERVICES }
        cmd: cd services/{{.ITEM}} && go mod tidy

  lint:
    desc: Run linting on all Go code
    cmds:
      - go vet ./...
      - for: { var: SERVICES }
        cmd: cd services/{{.ITEM}} && go vet ./...

  format:
    desc: Format all Go code
    cmds:
      - go fmt ./...
      - for: { var: SERVICES }
        cmd: cd services/{{.ITEM}} && go fmt ./...

  # Database Migrations
  migrate-up:
    desc: Run all migrations up for all services
    cmds:
      - task: migrate-up-auth

  migrate-up-auth:
    desc: Run migrations up for auth service
    env:
      AUTH_DATABASE_URL: postgres://auth_user:auth_password@localhost:5432/auth_db?sslmode=disable
    cmds:
      - migrate -path services/auth/migrations -database "{{.AUTH_DATABASE_URL}}" up

  migrate-up-feed:
    desc: Run migrations up for feed service  
    env:
      FEED_DATABASE_URL: postgres://feed_user:feed_password@localhost:5433/feed_db?sslmode=disable
    cmds:
      - migrate -path services/feed/migrations -database "{{.FEED_DATABASE_URL}}" up

  migrate-up-service:
    desc: Run migrations up for a specific service
    vars: { SERVICE: "" }
    cmds:
      - |
        {{if eq .SERVICE "auth"}}
        migrate -path services/auth/migrations -database "$env:AUTH_DATABASE_URL" up
        {{else if eq .SERVICE "feed"}}
        migrate -path services/feed/migrations -database "$env:FEED_DATABASE_URL" up
        {{else}}
        Write-Host "Unknown service: {{.SERVICE}}" && exit 1
        {{end}}

  migrate-down:
    desc: Run all migrations down for all services
    cmds:
      - task: migrate-down-auth

  migrate-down-auth:
    desc: Run migrations down for auth service
    env:
      AUTH_DATABASE_URL: postgres://auth_user:auth_password@localhost:5432/auth_db?sslmode=disable
    cmds:
      - migrate -path services/auth/migrations -database "{{.AUTH_DATABASE_URL}}" down

  migrate-down-feed:
    desc: Run migrations down for feed service
    env:
      FEED_DATABASE_URL: postgres://feed_user:feed_password@localhost:5433/feed_db?sslmode=disable
    cmds:
      - migrate -path services/feed/migrations -database "{{.FEED_DATABASE_URL}}" down

  migrate-down-service:
    desc: Run migrations down for a specific service
    vars: { SERVICE: "" }
    cmds:
      - |
        {{if eq .SERVICE "auth"}}
        migrate -path services/auth/migrations -database "$env:AUTH_DATABASE_URL" down
        {{else if eq .SERVICE "feed"}}
        migrate -path services/feed/migrations -database "$env:FEED_DATABASE_URL" down
        {{else}}
        Write-Host "Unknown service: {{.SERVICE}}" && exit 1
        {{end}}

  migrate-create-auth:
    desc: Create a new migration file for auth service
    vars: { NAME: "" }
    cmds:
      - migrate create -ext sql -dir services/auth/migrations -seq {{.NAME}}

  migrate-create-feed:
    desc: Create a new migration file for feed service  
    vars: { NAME: "" }
    cmds:
      - migrate create -ext sql -dir services/feed/migrations -seq {{.NAME}}

  migrate-force:
    desc: Force set migration version for a service
    vars: 
      SERVICE: ""
      VERSION: ""
    cmds:
      - |
        {{if eq .SERVICE "auth"}}
        migrate -path services/auth/migrations -database "$env:AUTH_DATABASE_URL" force {{.VERSION}}
        {{else if eq .SERVICE "feed"}}
        migrate -path services/feed/migrations -database "$env:FEED_DATABASE_URL" force {{.VERSION}}
        {{else}}
        Write-Host "Unknown service: {{.SERVICE}}" && exit 1
        {{end}}

  migrate-version-auth:
    desc: Check migration version for auth service
    env:
      AUTH_DATABASE_URL: postgres://auth_user:auth_password@localhost:5432/auth_db?sslmode=disable
    cmds:
      - migrate -path services/auth/migrations -database "{{.AUTH_DATABASE_URL}}" version

  migrate-version-feed:
    desc: Check migration version for feed service
    env:
      FEED_DATABASE_URL: postgres://feed_user:feed_password@localhost:5433/feed_db?sslmode=disable
    cmds:
      - migrate -path services/feed/migrations -database "{{.FEED_DATABASE_URL}}" version
